[package]
name = "idem"
version = "0.1.0"
authors = ["Julien Doutre <jul.doutre@gmail.com>"]
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
opentelemetry = "0.17"
opentelemetry-datadog = { version = "0.5.0", features = ["reqwest-blocking-client"] }
